#!/usr/bin/env bash
# This script stops the "7-highlander" process.

# Find the PID of the "7-highlander" process
PID=$(pgrep -f "7-highlander")

# If the PID is found, terminate the process
if [ -n "$PID" ]; then
    kill -15 "$PID"
    echo "Terminated"
else
    echo "Process not found"
fi

